In [2]:
import torch
import matplotlib as plt
%matplotlib inline

In [6]:
x = torch.empty(5,3)
print(x)

tensor([[5.0510e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


In [20]:
x = torch.randn(5,3,3,dtype=torch.float)
print(x)
print(torch.max(x,dim=0))

tensor([[[ 1.7089, -0.5424, -0.0335],
         [-0.8399,  0.2296, -0.6568],
         [ 0.1277, -0.4404,  0.0933]],

        [[ 0.6708, -0.4019, -1.5429],
         [-0.3755, -0.3601, -0.7769],
         [-0.6464,  0.7897,  0.6737]],

        [[-0.7301, -0.9427,  1.0767],
         [-0.8115, -1.0950, -0.0232],
         [ 0.1493, -0.5743,  0.2097]],

        [[-0.0483, -1.4432, -0.3215],
         [-0.1638, -0.3851, -0.4453],
         [-0.6400,  0.3886,  0.1858]],

        [[-0.1385, -0.0276, -1.6734],
         [-1.0308,  1.7437,  0.8106],
         [ 0.4945, -0.8656, -1.2537]]])
torch.return_types.max(
values=tensor([[ 1.7089, -0.0276,  1.0767],
        [-0.1638,  1.7437,  0.8106],
        [ 0.4945,  0.7897,  0.6737]]),
indices=tensor([[0, 4, 2],
        [3, 4, 4],
        [4, 1, 1]]))


In [9]:
x = torch.randn(4, 4)
# view to reshape a tensor
y = x.view(16)
z = x.view(2, -1)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.4758, -0.8062,  0.5574,  1.1061],
        [-2.2335,  0.8743,  0.6038, -1.0399],
        [ 0.3204, -0.3666,  3.1134,  0.2464],
        [-0.5373,  0.0087,  0.7361,  2.7307]])
tensor([ 1.4758, -0.8062,  0.5574,  1.1061, -2.2335,  0.8743,  0.6038, -1.0399,
         0.3204, -0.3666,  3.1134,  0.2464, -0.5373,  0.0087,  0.7361,  2.7307])
tensor([[ 1.4758, -0.8062,  0.5574,  1.1061, -2.2335,  0.8743,  0.6038, -1.0399],
        [ 0.3204, -0.3666,  3.1134,  0.2464, -0.5373,  0.0087,  0.7361,  2.7307]])


In [8]:
# The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.
a = torch.ones(2,5)
b = a.numpy()
print(torch.norm(a,dim=1,p=2))
print(b)
a.add_(1)
print(a)
print(b)

tensor([2.2361, 2.2361])
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [3]:
print(torch.cuda.is_available())

True
