In [1]:
import torch
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import nrrd
import random
import os

In [71]:
data_root = 'D:\\My\\MyCode\\PRSPaper\\PRSNet\\data\\bench'
start_file = 1
file_count = 1  # 151
view = True

In [72]:
for index in range(start_file, file_count+1):
    # read nrrd voxel data
    nrrd_path = os.path.join(data_root, str(index), 'model.nrrd')
    nrrd_data, nrrd_head = nrrd.read(nrrd_path)
    # print(nrrd_head)
    transform = transforms.ToTensor()
    voxel = transform(nrrd_data)
    voxel = voxel.view(1, 32, 32, 32)
#     print(voxel[0])

    # read pcd points data
    pcd_path = os.path.join(data_root, str(index), 'model.pcd')
    with open(pcd_path, mode='r') as pcd_data:
        # skip first 9 lines
        for i in range(9):
            pcd_data.readline()
        num_line = pcd_data.readline()
        num_points = num_line.split(' ')[1]
        pcd_data.readline()  # skip one more line
        points = []
        for i in range(int(num_points)):
            line = pcd_data.readline()
            point = line.split(' ')
            points.append([float(point[0]),
                           float(point[1]),
                           float(point[2])])
        print(num_points)



ValueError: invalid literal for int() with base 10: '16.786962509155273'

In [58]:
# uniform sample points
point = torch.tensor(points)
print(point[0])
print(len(point))
max, _ = torch.max(point, dim=0)
print(max)
min, _ = torch.min(point, dim=0)
print(min)

tensor([-0.1245, -0.1095, -0.4683])
1495
tensor([0.1299, 0.1174, 0.4683])
tensor([-0.1299, -0.1174, -0.4683])


In [59]:
point = point + 0.5 #以0，0，0为原点，边长为1的正方体包围盒
print(point)
point = point * 32
print(point)

tensor([[0.3755, 0.3905, 0.0317],
        [0.3920, 0.3974, 0.0317],
        [0.4299, 0.4102, 0.0380],
        ...,
        [0.4754, 0.6174, 0.9646],
        [0.5117, 0.6117, 0.9683],
        [0.6078, 0.6174, 0.9620]])
tensor([[12.0152, 12.4949,  1.0130],
        [12.5453, 12.7153,  1.0130],
        [13.7576, 13.1264,  1.2168],
        ...,
        [15.2122, 19.7578, 30.8682],
        [16.3755, 19.5749, 30.9870],
        [19.4504, 19.7578, 30.7842]])


In [60]:
%matplotlib qt
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.scatter(point[:, 0], point[:, 1], point[:, 2], color='r', s=1)
ax.view_init(45, 45)
ax.voxels(voxel[0], color='w', edgecolor="b")
plt.show()

In [25]:
a = torch.eye(3)
print(a)
print(a+0.5)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])
tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000]])


In [55]:
data_root = '..\\data\\bench'
start_file = 1
file_count = 1816
mark = '-skip'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
        pcd_path = os.path.join(data_root, subfolder, 'model.pcd')
        with open(pcd_path, mode='r') as pcd_data:
            # skip first 9 lines
            for i in range(9):
                pcd_data.readline()
            num_line = pcd_data.readline()
            num_points = num_line.split(' ')[1]
            pcd_data.readline()  # skip one more line
            points = []
            print(num_points)
        if int(num_points) < 1000:
            os.rename(os.path.join(data_root,subfolder),os.path.join(data_root,subfolder+mark))



1495

1501

1365

1332

1435

1457

1526

1365

1406

1408

1299

1289

1519

1430

1386

1435

1392

1532

1444

919

1297

1417

1448

1500

1296

1523

1450

1374

1449

511

1485

8

1221

1369

1391

1428

1508

1418

1317

1434

1172

1435

856

1470

1416

1350

1434

1460

1371

1429

1468

1136

1483

1358

1478

1523

1393

1457

1470

1092

1378

389

1458

1477

1412

1423

1509

1385

1494

1405

15

1418

1429

1313

1383

1475

1369

1417

1263

1365

1266

1484

1458

1437

1431

990

1498

1417

1405

1470

1370

1469

1399

1518

1319

608

1417

1342

1271

1524

1469

1451

1469

1391

1434

1461

1410

1462

1379

1372

1281

1444

1489

1512

1506

1443

1439

1322

1372

1429

1388

1399

1445

1420

1425

1324

1411

1462

1481

1507

390

1403

1287

1438

1461

1499

8

977

1416

1493

1402

1446

1376

1355

1402

1496

1445

16

1411

1339

1338

1048

1487

8

857

1399

1460

467

1515

1310

1491

1409

1164

1433

1503

1487

723

1449

1435

1400

1307


1347

838

1390

1493

1349

45

1433

1322

1431

1334

1364

1484

1327

1407

1432

1482

1475

1396

1432

1375

1231

16

1407

1470

1436

1349

1339

1147

1470

1390

1396

1371

1438

1494

1244

1389

1477

1439

1388

1429

538

1023

1432

1288

1381

1470

1505

1394

1493

1397

1457

1372

1548

1480

1458

1493

1286

1405

1374

1543

1406

1501

1506

30

1295

1241

1443

1360

1463

1367

132

1103

1427

1496

924

1454

1414

933

3

1453

1418

1468

1441

1489

1147

1369

1498

1436

1406

1435

1497

1422

1441

1366

1316

1433

1387

1249

1437

1502

1386

1348

1354

1416

1425

6

1430

1452

1444

1457

1219

1398

1514

1438

1437

1451

1282

1349

1324

1481

1436

1482

1407

1418

1408

1517

1410

1519

1358

723

435

1480

1295

1427

1464

1466

1307

1375

1491

1506

1512

1519

1365

1514

1297

1214

1469

1397

1236

1470

1434

1462

1512

1366

1339

1470

1343

1494

1351

1357

1456

1413

1326

1474

516

1351

1387

1454

1415

1037


In [ ]:
for index in range(start_file, file_count+1):
    # read pcd points data
    pcd_path = os.path.join(data_root, str(index), 'model.pcd')
    with open(pcd_path, mode='r') as pcd_data:
        # skip first 9 lines
        for i in range(9):
            pcd_data.readline()
        num_line = pcd_data.readline()
        num_points = num_line.split(' ')[1]
        pcd_data.readline()  # skip one more line
        points = []
        print(num_points)

In [75]:
data_root = '..\\data\\bench'
mark = '-skip'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
        if subfolder.find(mark) != -1:
            continue
        
#         # read nrrd voxel data
#         nrrd_path = os.path.join(data_root, subfolder, 'model.nrrd')
#         nrrd_data, nrrd_head = nrrd.read(nrrd_path)
#         # print(nrrd_head)
#         transform = transforms.ToTensor()
#         voxel = transform(nrrd_data)
#         voxel = voxel.view(1, 32, 32, 32)
    
        pcd_path = os.path.join(data_root, subfolder, 'model.pcd')
        with open(pcd_path, mode='r') as pcd_data:
            # skip first 9 lines
            for i in range(9):
                pcd_data.readline()
            num_line = pcd_data.readline()
            num_points = num_line.split(' ')[1]
            pcd_data.readline()  # skip one more line
            points = []
            print(num_points)

            for i in range(int(num_points)):
                line = pcd_data.readline()
                point = line.split(' ')
                points.append([float(point[0]),
                               float(point[1]),
                               float(point[2])])

        points = torch.tensor(points)
        max, _ = torch.max(points, dim=0)
        min, _ = torch.min(points, dim=0)
        points = points + 0.5 #以0，0，0为原点，边长为1的正方体包围盒
        points = points * 32
        points = random.sample(points,1000)
        
        # update point cloud data
        update_pcd_path = os.path.join(data_root, subfolder, 'model_uniform.pcd')
        with open(update_pcd_path, mode='w') as pcd_data:
            for i in range(len(points)):
                pcd_data.write('{} {} {}\n'.format(float(points[i][0]),
                                                   float(points[i][1]),
                                                   float(points[i][2])))


1495

1501

1365

1332

1435

1457

1526

1365

1406

1408

1299

1289

1519

1430

1386

1435

1392

1532

1444

1297

1417

1448

1500

1296

1523

1450

1374

1449

1485

1221

1369

1391

1428

1508

1418

1317

1434

1172

1435

1470

1416

1350

1434

1460

1371

1429

1468

1136

1483

1358

1478

1523

1393

1457

1470

1092

1378

1458

1477

1412

1423

1509

1385

1494

1405

1418

1429

1313

1383

1475

1369

1417

1263

1365

1266

1484

1458

1437

1431

1498

1417

1405

1470

1370

1469

1399

1518

1319

1417

1342

1271

1524

1469

1451

1469

1391

1434

1461

1410

1462

1379

1372

1281

1444

1489

1512

1506

1443

1439

1322

1372

1429

1388

1399

1445

1420

1425

1324

1411

1462

1481

1507

1403

1287

1438

1461

1499

1416

1493

1402

1446

1376

1355

1402

1496

1445

1411

1339

1338

1048

1487

1399

1460

1515

1310

1491

1409

1164

1433

1503

1487

1449

1435

1400

1307

1381

1466

1509

1497

1321

1396

1469

1376

1441

1338

1331

1325

1332

1419

1436

1417

1495

1296

1506

1401

1477

1346

1507

1437

1410

1289

1459

1464

1376

1393

1479

1412

1471

1358

1320

1353

1372

1398

1319

1433

1385

1007

1518

1461

1485

1456

1421

1443

1470

1490

1457

1299

1412

1077

1423

1484

1486

1443

1337

1477

1225

1472

1474

1397

1443

1473

1472

1449

1432

1354

1458

1526

1231

1437

1261

1446

1436

1527

1516

1426

1355

1446

1343

1369

1419

1393

1410

1456

1464

1474

1356

1464

1533

1426

1507

1502

1100

1316

1497

1299

1537

1522

1506

1321

1388

1467

1301

1383

1431

1451

1452

1441

1299

1479

1313

1516

1451

1492

1503

1397

1455

1378

1530

1417

1288

1453

1352

1473

1309

1508

1378

1329

1347

1390

1493

1349

1433

1322

1431

1334

1364

1484

1327

1407

1432

1482

1475

1396

1432

1375

1231

1407

1470

1436

1349

1339

1147

1470

1390

1396

1371

1438

1494

1244

1389

1477

1439

1388

1429

1023

1432

1288

1381

1470

1505

1394

1493

1397

1457

In [99]:
data_root = '..\\data\\bench'
mark = '-skip'
file_index = '4'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
#         print(subfolder)
        if subfolder.find(mark) != -1:
            continue
        
        if file_index is not subfolder:
            continue
        
        # read nrrd voxel data
        nrrd_path = os.path.join(data_root, subfolder, 'model.nrrd')
        nrrd_data, nrrd_head = nrrd.read(nrrd_path)
        # print(nrrd_head)
        transform = transforms.ToTensor()
        voxel = transform(nrrd_data)
        voxel = voxel.view(1, 32, 32, 32)

        
        # update point cloud data
        points=[]
        update_pcd_path = os.path.join(data_root, subfolder, 'model_uniform.pcd')
        with open(update_pcd_path, mode='r') as pcd_data:
            for i in pcd_data:
                xyz=i.strip('\n').split(' ')
                points.append([float(xyz[0]),float(xyz[1]),float(xyz[2])])
        points = torch.tensor(points)
        break
                


In [100]:
%matplotlib qt
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.scatter(points[:, 0], points[:, 1], points[:, 2], color='r', s=1)
ax.view_init(45, 45)
ax.voxels(voxel[0], color='w', edgecolor="b")
plt.show()

In [92]:
!"D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_viewer_release.exe" ..\data\bench\10\model.pcd

The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
[done, 140 ms : 1501 points]
Available dimensions: x y z


> Loading ..\data\bench\10\model.pcd 
