In [5]:
import torch
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import nrrd
import random
import os

In [57]:
# data_root = 'D:\\My\\MyCode\\PRSPaper\\PRSNet\\data\\bench'
data_root = 'D:\\My\\MyCode\\PRSPaper\\PRSNet\\data\\skateboard'
start_file = 1
file_count = 1  # 151
view = True

In [58]:
for index in range(start_file, start_file+file_count):
    # read nrrd voxel data
#     print(index)
    nrrd_path = os.path.join(data_root, str(index), 'model.nrrd')
    try:
        print(index)
        nrrd_data, nrrd_head = nrrd.read(nrrd_path)
#         print(nrrd_head)
        transform = transforms.ToTensor()
        voxel = transform(nrrd_data)
        voxel = voxel.view(1, 32, 32, 32)
    
    
        # read pcd points data
        pcd_path = os.path.join(data_root, str(index), 'model.pcd')
        with open(pcd_path, mode='r') as pcd_data:
            # skip first 9 lines
            for i in range(9):
                pcd_data.readline()
            num_line = pcd_data.readline()
            num_points = num_line.split(' ')[1]
            pcd_data.readline()  # skip one more line
            points = []
            for i in range(int(num_points)):
                line = pcd_data.readline()
                point = line.split(' ')
                points.append([float(point[0]),
                               float(point[1]),
                               float(point[2])])
    #       print(num_points)

        point = torch.tensor(points)
        max, _ = torch.max(point, dim=0)
        min, _ = torch.min(point, dim=0)
        max_dis = torch.max(max)

        print(torch.norm(max+min))
    except Exception as e:
        pass



1
tensor(0.0159)


In [35]:
# # uniform sample points
# point = torch.tensor(points)
# print(len(point))
# max, _ = torch.max(point, dim=0)
# print(max)
# min, _ = torch.min(point, dim=0)
# print(min)
# max_dis = torch.max(max)

# print(torch.norm(max+min))

1332
tensor([0.1197, 0.1576, 0.4589])
tensor([-0.1197, -0.1538, -0.4569])
tensor(0.0042)


In [59]:
point = point * 16 / max_dis #以0，0，0为原点，边长为1的正方体包围盒
print(point)
point = point +16
print(point)

tensor([[ -5.8431,   0.1250,  -4.7625],
        [ -5.2859,   0.1250,  -4.7753],
        [ -3.8088,   0.2538,  -4.7834],
        ...,
        [-11.6690,   0.1955,   4.7352],
        [-12.4939,   0.8311,   4.7642],
        [-12.2967,   0.7861,   4.7725]])
tensor([[10.1569, 16.1250, 11.2375],
        [10.7141, 16.1250, 11.2247],
        [12.1912, 16.2538, 11.2166],
        ...,
        [ 4.3310, 16.1955, 20.7352],
        [ 3.5061, 16.8311, 20.7642],
        [ 3.7033, 16.7861, 20.7725]])


In [60]:
%matplotlib qt
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.scatter(point[:, 0], point[:, 1], point[:, 2], color='r', s=1)
ax.view_init(45, 45)
ax.voxels(voxel[0], color='w', edgecolor="b")
plt.show()

In [61]:
data_root = '..\\data\\skateboard'
start_file = 1
file_count = 1816
mark = '-skip'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
        pcd_path = os.path.join(data_root, subfolder, 'model.pcd')
        with open(pcd_path, mode='r') as pcd_data:
            # skip first 9 lines
            for i in range(9):
                pcd_data.readline()
            num_line = pcd_data.readline()
            num_points = num_line.split(' ')[1]
            pcd_data.readline()  # skip one more line
            points = []
            print(num_points)
        if int(num_points) < 1000:
            os.rename(os.path.join(data_root,subfolder),os.path.join(data_root,subfolder+mark))



1302

1306

1216

1418

1294

1282

1340

1345

1318

1283

1240

1148

1246

1291

1347

1245

1302

1295

1295

1224

1278

1305

1146

1268

1348

1364

1326

1309

1285

1314

1345

1299

954

1284

1367

1320

1323

1325

1269

1283

1273

1314

1084

1291

1151

1159

1339

1407

1256

1242

1264

1304

1275

1311

1307

1323

1326

1266

1331

1263

1292

1345

1323

1015

944

1289

1305

1262

1262

1307

1302

1301

1249

1289

1200

1291

1169

1219

1288

1301

1283

1278

1319

1307

1265

1276

1324

88

1260

1235

1388

1213

1335

1360

1196

1221

1279

1325

1268

1338

1271

1059

1291

1318

1287

1328

1263

1323

1303

1354

1266

1302

1243

1244

1303

1289

1318

1222

1302

1338

1320

1248

1286

1339

1351

1167

1270

1290

1283

1282

1253

1121

1297

1331

1292

1168

1283

1249

1306

95

1343

1323

1288

1192

1297

1298

1299

1361

1090

1323

1147



In [ ]:
for index in range(start_file, file_count+1):
    # read pcd points data
    pcd_path = os.path.join(data_root, str(index), 'model.pcd')
    with open(pcd_path, mode='r') as pcd_data:
        # skip first 9 lines
        for i in range(9):
            pcd_data.readline()
        num_line = pcd_data.readline()
        num_points = num_line.split(' ')[1]
        pcd_data.readline()  # skip one more line
        points = []
        print(num_points)

In [75]:
data_root = '..\\data\\bench'
mark = '-skip'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
        if subfolder.find(mark) != -1:
            continue
        
#         # read nrrd voxel data
#         nrrd_path = os.path.join(data_root, subfolder, 'model.nrrd')
#         nrrd_data, nrrd_head = nrrd.read(nrrd_path)
#         # print(nrrd_head)
#         transform = transforms.ToTensor()
#         voxel = transform(nrrd_data)
#         voxel = voxel.view(1, 32, 32, 32)
    
        pcd_path = os.path.join(data_root, subfolder, 'model.pcd')
        with open(pcd_path, mode='r') as pcd_data:
            # skip first 9 lines
            for i in range(9):
                pcd_data.readline()
            num_line = pcd_data.readline()
            num_points = num_line.split(' ')[1]
            pcd_data.readline()  # skip one more line
            points = []
            print(num_points)

            for i in range(int(num_points)):
                line = pcd_data.readline()
                point = line.split(' ')
                points.append([float(point[0]),
                               float(point[1]),
                               float(point[2])])

        points = torch.tensor(points)
        max, _ = torch.max(points, dim=0)
        min, _ = torch.min(points, dim=0)
        points = points + 0.5 #以0，0，0为原点，边长为1的正方体包围盒
        points = points * 32
        points = random.sample(points,1000)
        
        # update point cloud data
        update_pcd_path = os.path.join(data_root, subfolder, 'model_uniform.pcd')
        with open(update_pcd_path, mode='w') as pcd_data:
            for i in range(len(points)):
                pcd_data.write('{} {} {}\n'.format(float(points[i][0]),
                                                   float(points[i][1]),
                                                   float(points[i][2])))


1495

1501

1365

1332

1435

1457

1526

1365

1406

1408

1299

1289

1519

1430

1386

1435

1392

1532

1444

1297

1417

1448

1500

1296

1523

1450

1374

1449

1485

1221

1369

1391

1428

1508

1418

1317

1434

1172

1435

1470

1416

1350

1434

1460

1371

1429

1468

1136

1483

1358

1478

1523

1393

1457

1470

1092

1378

1458

1477

1412

1423

1509

1385

1494

1405

1418

1429

1313

1383

1475

1369

1417

1263

1365

1266

1484

1458

1437

1431

1498

1417

1405

1470

1370

1469

1399

1518

1319

1417

1342

1271

1524

1469

1451

1469

1391

1434

1461

1410

1462

1379

1372

1281

1444

1489

1512

1506

1443

1439

1322

1372

1429

1388

1399

1445

1420

1425

1324

1411

1462

1481

1507

1403

1287

1438

1461

1499

1416

1493

1402

1446

1376

1355

1402

1496

1445

1411

1339

1338

1048

1487

1399

1460

1515

1310

1491

1409

1164

1433

1503

1487

1449

1435

1400

1307

1381

1466

1509

1497

1321

1396

1469

1376

1441

1338

1331

1325

1332

1419

1436

1417

1495

1296

1506

1401

1477

1346

1507

1437

1410

1289

1459

1464

1376

1393

1479

1412

1471

1358

1320

1353

1372

1398

1319

1433

1385

1007

1518

1461

1485

1456

1421

1443

1470

1490

1457

1299

1412

1077

1423

1484

1486

1443

1337

1477

1225

1472

1474

1397

1443

1473

1472

1449

1432

1354

1458

1526

1231

1437

1261

1446

1436

1527

1516

1426

1355

1446

1343

1369

1419

1393

1410

1456

1464

1474

1356

1464

1533

1426

1507

1502

1100

1316

1497

1299

1537

1522

1506

1321

1388

1467

1301

1383

1431

1451

1452

1441

1299

1479

1313

1516

1451

1492

1503

1397

1455

1378

1530

1417

1288

1453

1352

1473

1309

1508

1378

1329

1347

1390

1493

1349

1433

1322

1431

1334

1364

1484

1327

1407

1432

1482

1475

1396

1432

1375

1231

1407

1470

1436

1349

1339

1147

1470

1390

1396

1371

1438

1494

1244

1389

1477

1439

1388

1429

1023

1432

1288

1381

1470

1505

1394

1493

1397

1457

In [99]:
data_root = '..\\data\\bench'
mark = '-skip'
file_index = '4'
for foldName, subfolders, filenames in os.walk(data_root):     #用os.walk方法取得path路径下的文件夹路径，子文件夹名，所有文件名
    for subfolder in subfolders:     #遍历列表下的子文件夹名
#         print(subfolder)
        if subfolder.find(mark) != -1:
            continue
        
        if file_index is not subfolder:
            continue
        
        # read nrrd voxel data
        nrrd_path = os.path.join(data_root, subfolder, 'model.nrrd')
        nrrd_data, nrrd_head = nrrd.read(nrrd_path)
        # print(nrrd_head)
        transform = transforms.ToTensor()
        voxel = transform(nrrd_data)
        voxel = voxel.view(1, 32, 32, 32)

        
        # update point cloud data
        points=[]
        update_pcd_path = os.path.join(data_root, subfolder, 'model_uniform.pcd')
        with open(update_pcd_path, mode='r') as pcd_data:
            for i in pcd_data:
                xyz=i.strip('\n').split(' ')
                points.append([float(xyz[0]),float(xyz[1]),float(xyz[2])])
        points = torch.tensor(points)
        break
                


In [100]:
%matplotlib qt
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.scatter(points[:, 0], points[:, 1], points[:, 2], color='r', s=1)
ax.view_init(45, 45)
ax.voxels(voxel[0], color='w', edgecolor="b")
plt.show()

In [67]:
# !"D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_viewer_release.exe" ..\data\bench\37\model.pcd
!"D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_viewer_release.exe" ..\scripts\model.pcd

The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
[done, 1094 ms : 4740 points]
Available dimensions: x y z


> Loading ..\scripts\model.pcd 


In [68]:
!"D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_mesh2pcd_release.exe" ..\data\bench\37\model.obj ..\scripts\model.pcd 

Convert a CAD model to a point cloud using ray tracing operations. For more information, use: D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_mesh2pcd_release.exe -h


In [64]:
!"D:\ThunderDownload\software\PCL\PCL 1.8.1\bin\pcl_viewer_release.exe" ..\data\skateboard\41-skip\model.pcd

The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
[done, 212 ms : 88 points]
Available dimensions: x y z


> Loading ..\data\skateboard\41-skip\model.pcd 
